[phases.setup]
nixPkgs = ["python311", "nodejs", "playwright"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps chromium"
]

[start]
cmd = "python backend.py"
